/**
 * SEVEN MINERALS + SEVEN HERITAGE — canonical colour palette snapshot.
 *
 * AUTO-GENERATED by `scripts/sync-tokens.ts` from the Supabase document store
 * (collections `styling-minerals` and `styling-heritage-colors`). The database
 * is the single source of truth — DO NOT EDIT THIS FILE BY HAND.
 *
 *   pnpm tokens:sync     regenerate this file + the globals.css palette block
 *   pnpm tokens:verify   CI gate — fails if this snapshot drifts from the DB
 *
 * Two mineral families: `deep-earth` (cobalt, tanzanite, malachite, sodalite)
 * and `hand` (gold, terracotta, copper). Heritage tones are atmospheric
 * anchors with no family/role.
 */

export interface MineralToken {
  name: string
  role: string
  family: "deep-earth" | "hand"
  cssVar: string
  darkHex: string
  lightHex: string
  containerDark: string
  containerLight: string
  onContainerDark: string
  onContainerLight: string
  sortOrder: number
  origin: string
  symbolism: string
  usage: string
}

export interface HeritageToken {
  name: string
  cssVar: string
  darkHex: string
  lightHex: string
  sortOrder: number
  origin: string
  symbolism: string
  usage: string
}

export const minerals: MineralToken[] = [
  {
    name: "cobalt",
    role: "Knowledge",
    family: "deep-earth",
    cssVar: "--color-cobalt",
    darkHex: "#00B0FF",
    lightHex: "#0047AB",
    containerDark: "#001F3F",
    containerLight: "#E3F2FD",
    onContainerDark: "#B3E5FC",
    onContainerLight: "#002966",
    sortOrder: 0,
    origin: "Katanga (DRC) and Zambian Copperbelt",
    symbolism: "Digital future, trust, knowledge",
    usage: "Primary blue, links, CTAs",
  },
  {
    name: "tanzanite",
    role: "Identity",
    family: "deep-earth",
    cssVar: "--color-tanzanite",
    darkHex: "#B388FF",
    lightHex: "#4B0082",
    containerDark: "#1A0033",
    containerLight: "#F3E5F5",
    onContainerDark: "#E1BEE7",
    onContainerLight: "#2E004D",
    sortOrder: 1,
    origin: "Merelani Hills, Tanzania",
    symbolism: "Premium, creativity, connection",
    usage: "Purple accent, brand/logo, social features",
  },
  {
    name: "malachite",
    role: "Growth",
    family: "deep-earth",
    cssVar: "--color-malachite",
    darkHex: "#64FFDA",
    lightHex: "#004D40",
    containerDark: "#00251A",
    containerLight: "#E0F2F1",
    onContainerDark: "#A7FFEB",
    onContainerLight: "#00332B",
    sortOrder: 2,
    origin: "Congo Copper Belt",
    symbolism: "Growth, nature, success",
    usage: "Success states, positive actions",
  },
  {
    name: "gold",
    role: "Value",
    family: "hand",
    cssVar: "--color-gold",
    darkHex: "#FFD740",
    lightHex: "#5D4037",
    containerDark: "#332200",
    containerLight: "#FFF8E1",
    onContainerDark: "#FFECB3",
    onContainerLight: "#3E2723",
    sortOrder: 3,
    origin: "Ghana, South Africa, Mali",
    symbolism: "Honey, rewards, warmth",
    usage: "Achievements, rewards, highlights",
  },
  {
    name: "terracotta",
    role: "Community",
    family: "hand",
    cssVar: "--color-terracotta",
    darkHex: "#E1B07E",
    lightHex: "#A0522D",
    containerDark: "#3E2817",
    containerLight: "#F5E6D3",
    onContainerDark: "#F5E6D3",
    onContainerLight: "#5D2906",
    sortOrder: 4,
    origin: "Pan-African Sahel",
    symbolism: "Earth, community, grounding",
    usage: "Community features, warmth",
  },
  {
    name: "sodalite",
    role: "Intelligence",
    family: "deep-earth",
    cssVar: "--color-sodalite",
    darkHex: "#3D5AFE",
    lightHex: "#283593",
    containerDark: "#0D1442",
    containerLight: "#E8EAF6",
    onContainerDark: "#C5CAE9",
    onContainerLight: "#141A5C",
    sortOrder: 5,
    origin: "Kunene River, Namibia & South Africa",
    symbolism: "Intelligence, depth, reasoning",
    usage: "AI/Shamwari surfaces, deep-reasoning states",
  },
  {
    name: "copper",
    role: "Stewardship",
    family: "hand",
    cssVar: "--color-copper",
    darkHex: "#FF8A65",
    lightHex: "#BF5A36",
    containerDark: "#3A1A0E",
    containerLight: "#FBE4DA",
    onContainerDark: "#FFD3C2",
    onContainerLight: "#5C2410",
    sortOrder: 6,
    origin: "Central African Copperbelt, Zambia & DRC",
    symbolism: "Connection, foundation, stewardship",
    usage: "Bundu ecosystem identity, the commons",
  },
]

export const heritageColors: HeritageToken[] = [
  {
    name: "indigo",
    cssVar: "--color-indigo",
    darkHex: "#7986CB",
    lightHex: "#4527A0",
    sortOrder: 0,
    origin: "Indigofera, West Africa textile tradition",
    symbolism: "Dusk, depth, the dyer's craft",
    usage: "Twilight surfaces, deep atmosphere, mini-app moods",
  },
  {
    name: "savanna",
    cssVar: "--color-savanna",
    darkHex: "#E5C158",
    lightHex: "#8D6E1A",
    sortOrder: 1,
    origin: "Sub-Saharan grasslands",
    symbolism: "Sun-dried grass, open land, the dry season",
    usage: "Warm grassland surfaces, daylight atmosphere",
  },
  {
    name: "baobab",
    cssVar: "--color-baobab",
    darkHex: "#A1887F",
    lightHex: "#4E342E",
    sortOrder: 2,
    origin: "Adansonia, across the African continent",
    symbolism: "The tree of life, age, shelter",
    usage: "Earthy surfaces, grounded atmosphere, bark tones",
  },
  {
    name: "sunset",
    cssVar: "--color-sunset",
    darkHex: "#FF7043",
    lightHex: "#D84315",
    sortOrder: 3,
    origin: "The African horizon at dusk",
    symbolism: "Day's end, warmth, the gathering hour",
    usage: "Warm accent surfaces, golden-hour atmosphere",
  },
  {
    name: "river",
    cssVar: "--color-river",
    darkHex: "#4DD0E1",
    lightHex: "#006064",
    sortOrder: 4,
    origin: "The great African rivers — Zambezi, Nile, Congo",
    symbolism: "Flow, life, the journey",
    usage: "Cool surfaces, flowing atmosphere, water tones",
  },
  {
    name: "hematite",
    cssVar: "--color-hematite",
    darkHex: "#90A4AE",
    lightHex: "#546E7A",
    sortOrder: 5,
    origin: "Sishen & Thabazimbi, South Africa",
    symbolism: "Foundation, endurance, the substrate",
    usage: "Neutral anchor, mini-app surfaces, atmosphere",
  },
  {
    name: "kalahari",
    cssVar: "--color-kalahari",
    darkHex: "#E8D9B5",
    lightHex: "#C9B589",
    sortOrder: 6,
    origin: "Kalahari & Namib, Southern Africa",
    symbolism: "Openness, space, the light pole",
    usage: "Light anchor, warm backgrounds, mini-app surfaces",
  },
]
